add 2 rest request for pizza task
shift-intensiv/backend pull request #1
Opened 2024-04-22 03:20 UTC by anv296

2024-04-22 04:42 UTC, debabin requested changes

2024-04-22 04:42 UTC, debabin commented on src/modules/pizza/entities/pizza-dough.entity.ts
> +  THICK = 'Толстое'
надо на фронт возращать на англ ключи

2024-04-22 04:42 UTC, debabin commented on src/modules/pizza/entities/pizza-ingredient.entity.ts
> +export enum Ingredient {
тут тоже самое, это должны парсить фронты

2024-04-22 04:42 UTC, debabin commented on src/modules/pizza/modules/pizza-order/pizza-order.entity.ts
> +  person: PizzaPerson;
фио можно не писать, можно тут оставить просто номер

2024-04-22 04:42 UTC, debabin commented on src/modules/pizza/modules/pizza-order/pizza-order.service.ts
> +  @Cron('0 0 */5 * * *')
тут время поменять, чтобы каждые 20 минут

2024-04-22 04:42 UTC, debabin commented on src/modules/pizza/modules/pizza-order/pizza-order.entity.ts
> +});
Вот тут гуд enum

2024-04-24 07:52 UTC, anv296 commented on src/modules/pizza/modules/pizza-order/pizza-order.entity.ts
> +  person: PizzaPerson;
думаю оставить для увеличения объема работы студентов

2024-05-08 08:59 UTC, debabin requested changes

2024-05-08 08:59 UTC, debabin commented on src/modules/delivery/modules/delivery-order/delivery-order.service.ts
> +  @Cron('*/20 * * * *')
тут стоит каждые 20 секунд, надо бы исправить на часы

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/index.ts
пустой файл

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/modules/pizza-order/pizza-order.service.ts
> +  @Cron('*/20 * * * *')
также 20 секунд

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/modules/pizza-order/pizza-order.service.ts
> +  }
в нейминге остался deliveries

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/pizza.controller.ts
> +  async getDeliveries(@Req() request: Request): Promise<PizzaOrdersResponse> {
в нейминге осталось доставка, проверить по файлу

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/pizza.controller.ts
> +    const decodedJwtAccessToken = (await this.authService.decode(token)) as User;
давай вынесем в функции и используем везде в коде

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/pizza.controller.ts
> +  async getDelivery(
доставка

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/pizza.query.ts
> +  async getDeliveries(@Context() context: { req: Request }): Promise<PizzaOrdersResponse> {
нейминг, странно что у тебя не ругается код, ведь не может в системе быть 2 мутации с одним и тем же неймингом

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/pizza.query.ts
> +  async getDelivery(
нейминг

2024-05-08 08:59 UTC, debabin commented on src/modules/pizza/pizza.query.ts
> +  @Query(() => PizzaOrderResponse)
А еще это не думаю что править надо, но у нас нейминг странный тут PizzaOrderResponse, хотя ниже ща будет getOrder просто, но выше например getPizzas, хотя это по факту getCatalog, но при этом еще и ответ CatalogResponse

2024-05-08 09:01 UTC, debabin requested changes

2024-05-08 09:01 UTC, debabin commented on src/modules/pizza/entities/address.entity.ts
> +export class PersonAddress {
файл просто называет address, хотя тут perso address

2024-05-15 08:30 UTC, anv296 commented on src/modules/pizza/entities/address.entity.ts
> +export class PersonAddress {
в доставке добавить деливери, а тут пицца

2024-05-19 07:21 UTC, debabin approved these changes

2024-06-01 10:31 UTC, merged